---
abstract: 'Form Based Authentication for Plack (think CatalystX::Simple)'
author:
  - 'Zbigniew Lukasiak <zby@cpan.org>'
build_requires:
  Data::Dumper: 0
  Test::More: 0
  Test::WWW::Mechanize::PSGI: 0
configure_requires:
  ExtUtils::MakeMaker: 6.31
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200004, CPAN::Meta::Converter version 2.110240'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Plack-Middleware-Login
no_index:
  directory:
    - t/lib
    - examples
    - extensions
requires:
  Plack::Middleware: 0
  Plack::Request: 0
  Plack::Util::Accessor: 0
  Scalar::Util: 0
  parent: 0
resources: {}
version: 0.001
